apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432 # Port to be visible inside of network
      targetPort: 5432
  type: ClusterIP # For security reasons database is visible only inside of cluster